/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    MyFooter: typeof import('./src/components/navigation/footer/MyFooter.vue')['default']
    MyHeader: typeof import('./src/components/navigation/header/MyHeader.vue')['default']
    MyLoader: typeof import('./src/components/shared/loader/MyLoader.vue')['default']
    MyMenu: typeof import('./src/components/shared/menu/MyMenu.vue')['default']
    MyMenuItem: typeof import('./src/components/shared/menu/MyMenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
